version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/unifiedappadminfrontend

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: "755"

hooks:
  ApplicationStart:
    - location: /install.sh
      timeout: 300
      runas: ubuntu